# Generated by Django 5.1.1 on 2024-09-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Multiple Choice'), (2, 'Free Text')])),
                ('position', models.IntegerField(help_text='Positioned in ascending order, starting from 0')),
                ('is_active', models.BooleanField(default=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score awarded for a correct answer.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('position', models.IntegerField(help_text='Positioned in ascending order')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='activities.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_type', models.PositiveSmallIntegerField(choices=[(1, 'All questions in one page'), (2, 'One question per page')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived'), (4, 'Scheduled'), (5, 'Closed'), (6, 'Reviewing'), (7, 'In Progress')], default=1)),
                ('random_ordering', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='test duration in minutes', null=True)),
                ('access_code', models.CharField(blank=True, help_text='Optional access code for restricted quizzes', max_length=20)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='instructors.instructor')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.quiz'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Assignment'), (2, 'Quiz')], default=2)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.quiz')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
